.TH "environnement.Object" 3 "Thu Oct 6 2016" "Version 1.0" "IA-Aspirateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
environnement.Object \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObject\fP (\fBType\fP t)"
.br
.ti -1c
.RI "\fBType\fP \fBgetType\fP ()"
.br
.ti -1c
.RI "void \fBsetType\fP (\fBType\fP type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe représentant un objet présent sur une cellule Cette classe a été implementée dans l'optique d'ajouter des contraintes sur ces objets telles que le poids Cette fonctionnalité n'a pas encore été développée\&. 
.PP
\fBAuthor:\fP
.RS 4
Thomas 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "environnement\&.Object\&.Object (\fBType\fP t)"
Constructeur de la classe 
.PP
\fBParameters:\fP
.RS 4
\fIt\fP \fBType\fP de l'objet 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBType\fP environnement\&.Object\&.getType ()"
Getter du type de l'objet 
.PP
\fBReturns:\fP
.RS 4
Le type de l'objet 
.RE
.PP

.SS "void environnement\&.Object\&.setType (\fBType\fP type)"
Setter du type de l'objet 
.PP
\fBParameters:\fP
.RS 4
\fItype\fP Le type de l'objet 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for IA-Aspirateur from the source code\&.
