.TH "graphic.PopupMenu" 3 "Thu Oct 6 2016" "Version 1.0" "IA-Aspirateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphic.PopupMenu \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits JPopupMenu\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopupMenu\fP (\fBCellPane\fP c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe qui représente le menu contextuel d'une cellule 
.PP
\fBAuthor:\fP
.RS 4
Maxime 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "graphic\&.PopupMenu\&.PopupMenu (\fBCellPane\fP c)"
Constructeur de la classe qui permet d'initialiser le menu ainsi que les listeneners 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP = la cellule mère 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for IA-Aspirateur from the source code\&.
