.TH "IA.Direction" 3 "Thu Oct 6 2016" "Version 1.0" "IA-Aspirateur" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IA.Direction \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLEFT\fP"
.br
.ti -1c
.RI "\fBRIGHT\fP"
.br
.ti -1c
.RI "\fBUP\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
quentin 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for IA-Aspirateur from the source code\&.
