/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Classe principale de l'interface graphique.
 * Elle permet d'initialiser la grille et d'ajouter les éléments graphiques
 * utilisable par les utilisateurs.
 * @author Maxime
 */
public class Main extends javax.swing.JFrame implements Runnable{

    /**
     * Variable qui représente la classe principale du projet
     * et qui permet de faire le lien avec les autres classes du projet
     */
    private main.Main main;
    /**
     * Constructeur de la classe qui permet d'initialiser la variable main
     * @param main Classe principale du projet
     */
    public Main(main.Main main) {
        this.main = main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new graphic.GridPanel();
        labelTime = new javax.swing.JLabel();
        sliderTime = new javax.swing.JSlider();
        textFieldTime = new javax.swing.JTextField();
        labelDust = new javax.swing.JLabel();
        sliderDust = new javax.swing.JSlider();
        textFieldDust = new javax.swing.JTextField();
        labelJewel = new javax.swing.JLabel();
        sliderJewel = new javax.swing.JSlider();
        textFieldJewel = new javax.swing.JTextField();
        labelEnergy = new javax.swing.JLabel();
        energy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 720));

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 453, Short.MAX_VALUE)
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTime.setLabelFor(sliderTime);
        labelTime.setText("Time to loop for apparition (in s)");

        sliderTime.setMaximum(10);
        sliderTime.setMinimum(1);
        sliderTime.setValue(2);
        sliderTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTimeStateChanged(evt);
            }
        });

        textFieldTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldTime.setText("2");
        textFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTimeActionPerformed(evt);
            }
        });

        labelDust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDust.setLabelFor(sliderTime);
        labelDust.setText("Dust probability");

        sliderDust.setValue(20);
        sliderDust.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDustStateChanged(evt);
            }
        });

        textFieldDust.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldDust.setText("20");
        textFieldDust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDustActionPerformed(evt);
            }
        });

        labelJewel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJewel.setLabelFor(sliderTime);
        labelJewel.setText("Jewel probability");

        sliderJewel.setValue(10);
        sliderJewel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderJewelStateChanged(evt);
            }
        });

        textFieldJewel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldJewel.setText("10");
        textFieldJewel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldJewelActionPerformed(evt);
            }
        });

        labelEnergy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEnergy.setText("Consumed energy");

        energy.setBackground(new java.awt.Color(0, 0, 0));
        energy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        energy.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJewel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addComponent(sliderDust, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEnergy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(energy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderJewel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldJewel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldDust)
                    .addComponent(textFieldTime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderDust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJewel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderJewel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldJewel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEnergy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(energy)
                .addContainerGap(354, Short.MAX_VALUE))
            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Méthode qui permet de mettre à jour le champs texte de la fréquence 
     * lorsque le slider de la fréquence est modifié
     * @param evt 
     */
    private void sliderTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTimeStateChanged
        textFieldTime.setText(Integer.toString(sliderTime.getValue()));
        main.setFrequency(sliderTime.getValue());
    }//GEN-LAST:event_sliderTimeStateChanged
    /**
     * Méthode qui permet de mettre à jour le champs texte de la prob de la 
     * poussière lorsque le slider de la poussière est modifié 
     * @param evt 
     */
    private void sliderDustStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDustStateChanged
        textFieldDust.setText(Integer.toString(sliderDust.getValue()));
        main.setDustProb(sliderDust.getValue());
    }//GEN-LAST:event_sliderDustStateChanged
    /**
     * Méthode qui permet de mettre à jour le champs texte de la prob du bijou 
     * lorsque le slider du bijou est modifié
     * @param evt 
     */
    private void sliderJewelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderJewelStateChanged
        textFieldJewel.setText(Integer.toString(sliderJewel.getValue()));
        main.setJewelProb(sliderJewel.getValue());
    }//GEN-LAST:event_sliderJewelStateChanged
    /**
     * Méthode qui permet de mettre à jour le slider de la frequence
     * lorsque la valeur du champs texte de la fréquence est modifiée
     * @param evt 
     */
    private void textFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTimeActionPerformed
        sliderTime.setValue(Integer.parseInt(textFieldTime.getText()));
        main.setFrequency(Integer.parseInt(textFieldTime.getText()));
    }//GEN-LAST:event_textFieldTimeActionPerformed
    /**
     * Méthode qui permet de mettre à jour le slider de la prob de la
     * poussière lorsque la valeur du champs texte de la prob de la 
     * poussière est modifiée
     * @param evt 
     */
    private void textFieldDustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDustActionPerformed
        sliderDust.setValue(Integer.parseInt(textFieldDust.getText()));
        main.setDustProb(Integer.parseInt(textFieldDust.getText()));
    }//GEN-LAST:event_textFieldDustActionPerformed
    /**
     * Méthode qui permet de mettre à jour le slider de la prob du bijou
     * lorsque la valeur du champs texte de la prob du bijou est modifiée
     * @param evt 
     */
    private void textFieldJewelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldJewelActionPerformed
        sliderJewel.setValue(Integer.parseInt(textFieldJewel.getText()));
        main.setJewelProb(Integer.parseInt(textFieldJewel.getText()));
    }//GEN-LAST:event_textFieldJewelActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main(main.Main).setVisible(true);
//            }
//        });
//    }

    /**
     * energy = label texte qui affiche l'énergie dépensée
     * labelDust = label qui affiche le texte ""
     * labelEnergy = label qui affiche le texte ""
     * labelJewel = label qui affiche le texte ""
     * sliderDust = slider de la probabilité d'avoir une poussière
     * sliderJewel = slider de la probabilité d'avoir un bijou
     * sliderTime = slider de la fréquence d'apparition d'un item
     * textFieldDust = champs texte qui affiche la probabilité d'avoir une 
     * poussière
     * textFieldJewel = champs texte qui affiche la probabilité d'avoir un bijou
     * textFieldDust = champs texte qui affiche la fréquence d'apparition d'un
     * item
     * view = la grille qui va recevoir l'affichage des items 
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel energy;
    private javax.swing.JLabel labelDust;
    private javax.swing.JLabel labelEnergy;
    private javax.swing.JLabel labelJewel;
    private javax.swing.JLabel labelTime;
    private javax.swing.JSlider sliderDust;
    private javax.swing.JSlider sliderJewel;
    private javax.swing.JSlider sliderTime;
    private javax.swing.JTextField textFieldDust;
    private javax.swing.JTextField textFieldJewel;
    private javax.swing.JTextField textFieldTime;
    public graphic.GridPanel view;
    // End of variables declaration//GEN-END:variables

    /**
     * Méthode qui permet d'initialiser tous les composants graphiques ainsi 
     * que d'initialiser la grille et ses cellules
     */
    @Override
    public void run() {
        //initiliase les composants graphiques
        initComponents();
        //Création de la grille et de ses cellules
        view.initialize(this);
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(true);
    }

    /**
     * Getter du main
     * @return the main
     */
    public main.Main getMain() {
        return main;
    }

    /**
     * Setter du main 
     * @param main the main to set
     */
    public void setMain(main.Main main) {
        this.main = main;
    }
    /**
     * Setter de l'energie 
     * permet de modifer le champs de l'énergie
     * @param s représente la valeur
     */
    public void setEnergy(String s){
        this.energy.setText(s);
    }
}
