/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Thomas
 */
public class Main extends javax.swing.JFrame implements Runnable{

    private main.Main main;
    /**
     * Creates new form Main
     */
    public Main(main.Main main) {
        this.main = main;
        
//        view.addD(0,0);
//        view.addJ(0,0);
//        view.delJ(0, 0);
//        view.addR(0,0);
//        view.delJ(0,0);
//        view.delD(0,0);
//        view.mvtR(0,0,0,1);
      //view.delJ(0,0);
//      view.addD(2,2);
//      view.addJ(2,2);
//      view.addR(2, 2);
//      view.delR(2, 2);

//      view.addJ(1,0);
//      view.delJ(1,0);
//      view.addD(1,0);
//      view.addJ(0,0);
//      view.addD(0,0);
//      view.delD(0,0);
//      view.addD(2,2);
//      view.mvtR(0,1,0,2);
//      view.mvtR(0,2,1,2);
//      view.addD(2,1);
//      view.addJ(2,1);
//      view.mvtR(1,2,2,2);
//      view.mvtR(2,2,2,1);
      
////        view.addR(0,0);
////        view.mvtR(0, 0, 1, 0);
////        view.addJ(1,0);
////        view.addD(1,0);
//      view.delR(2, 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        view = new graphic.GridPanel();
        labelTime = new javax.swing.JLabel();
        sliderTime = new javax.swing.JSlider();
        textFieldTime = new javax.swing.JTextField();
        labelDust = new javax.swing.JLabel();
        sliderDust = new javax.swing.JSlider();
        textFieldDust = new javax.swing.JTextField();
        labelJewel = new javax.swing.JLabel();
        sliderJewel = new javax.swing.JSlider();
        textFieldJewel = new javax.swing.JTextField();
        labelEnergy = new javax.swing.JLabel();
        energy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTime.setLabelFor(sliderTime);
        labelTime.setText("Time to loop for apparition (in s)");

        sliderTime.setMaximum(10);
        sliderTime.setMinimum(1);
        sliderTime.setValue(2);
        sliderTime.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTimeStateChanged(evt);
            }
        });

        textFieldTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldTime.setText("2");
        textFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldTimeActionPerformed(evt);
            }
        });

        labelDust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDust.setLabelFor(sliderTime);
        labelDust.setText("Dust probability");

        sliderDust.setValue(20);
        sliderDust.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderDustStateChanged(evt);
            }
        });

        textFieldDust.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldDust.setText("20");
        textFieldDust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDustActionPerformed(evt);
            }
        });

        labelJewel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelJewel.setLabelFor(sliderTime);
        labelJewel.setText("Jewel probability");

        sliderJewel.setValue(10);
        sliderJewel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderJewelStateChanged(evt);
            }
        });

        textFieldJewel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldJewel.setText("10");
        textFieldJewel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldJewelActionPerformed(evt);
            }
        });

        labelEnergy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEnergy.setText("Consumed energy");

        energy.setBackground(new java.awt.Color(0, 0, 0));
        energy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        energy.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelJewel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(sliderDust, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelEnergy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(energy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderJewel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldJewel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldDust)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTime)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(labelDust)
                        .addContainerGap())
                    .addComponent(textFieldTime, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDust)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderDust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJewel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sliderJewel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldJewel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelEnergy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(energy)
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderTimeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTimeStateChanged
        textFieldTime.setText(Integer.toString(sliderTime.getValue()));
        main.setFrequency(sliderTime.getValue());
    }//GEN-LAST:event_sliderTimeStateChanged

    private void sliderDustStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderDustStateChanged
        textFieldDust.setText(Integer.toString(sliderDust.getValue()));
        main.setDustProb(sliderDust.getValue());
    }//GEN-LAST:event_sliderDustStateChanged

    private void sliderJewelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderJewelStateChanged
        textFieldJewel.setText(Integer.toString(sliderJewel.getValue()));
        main.setJewelProb(sliderJewel.getValue());
    }//GEN-LAST:event_sliderJewelStateChanged

    private void textFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldTimeActionPerformed
        sliderTime.setValue(Integer.parseInt(textFieldTime.getText()));
        main.setFrequency(Integer.parseInt(textFieldTime.getText()));
    }//GEN-LAST:event_textFieldTimeActionPerformed

    private void textFieldDustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDustActionPerformed
        sliderDust.setValue(Integer.parseInt(textFieldDust.getText()));
        main.setDustProb(Integer.parseInt(textFieldDust.getText()));
    }//GEN-LAST:event_textFieldDustActionPerformed

    private void textFieldJewelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldJewelActionPerformed
        sliderJewel.setValue(Integer.parseInt(textFieldJewel.getText()));
        main.setJewelProb(Integer.parseInt(textFieldJewel.getText()));
    }//GEN-LAST:event_textFieldJewelActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Main(main.Main).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel energy;
    private javax.swing.JLabel labelDust;
    private javax.swing.JLabel labelEnergy;
    private javax.swing.JLabel labelJewel;
    private javax.swing.JLabel labelTime;
    private javax.swing.JSlider sliderDust;
    private javax.swing.JSlider sliderJewel;
    private javax.swing.JSlider sliderTime;
    private javax.swing.JTextField textFieldDust;
    private javax.swing.JTextField textFieldJewel;
    private javax.swing.JTextField textFieldTime;
    public graphic.GridPanel view;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        initComponents();
        view.initialize(this);
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(true);
    }

    /**
     * @return the main
     */
    public main.Main getMain() {
        return main;
    }

    /**
     * @param main the main to set
     */
    public void setMain(main.Main main) {
        this.main = main;
    }
    
    public void setEnergy(String s){
        this.energy.setText(s);
    }
}
